spring:
  application:
    name: kafka-spring-demo
  # Kafka 配置项
  kafka:
    bootstrap-servers: 150.158.119.205:9092,120.55.167.193:9092,117.72.37.81:9092  # Kafka Broker 地址，可以设置多个
    # Kafka Producer 配置项
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # 消息的 key 的序列化器
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # 消息的 value 的序列化器
      acks: 1  # 0-不应答 / 1-leader应答 / all-所有leader和follower应答
      retries: 3  # 发送失败时，重试发送的次数
      batch-size: 16384  # 每次批量发送消息的最大数量（默认 16KB）
      buffer-memory: 33554432  # 每次批量发送消息的最大内存（默认32M）
      #transaction-id-prefix: tx_  # 加事务前缀（相当于自动开启事务）
      properties:
        linger:
          ms: 1000  # 批处理延迟时间上限，达到时间上限后，直接发送一次消息
    # Kafka Consumer 配置项
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false  # 关闭自动提交，如果开启消费者每次消费后自动发送 ack，由于自动确认有延迟，消费者重启可能导致重复消费
      auto-commit-interval: 1000
      auto-offset-reset: earliest # 设置消费者组最初的消费进度为 earliest
    # Kafka Consumer Listener 监听器配置
    listener:
      missing-topics-fatal: false  # 消费监听接口监听的主题不存在时，默认会报错，设置为 false 可解决报错
      ack-mode: manual  # MANUAL模式：先标记提交消费进度，消费完成后再提交消费进度
